from environs import Env

env = Env()
env.read_env()

DATABASE_URL = env.str("DATABASE_URL")
JWT_SECRET = env.str("JWT_SECRET")
JWT_ALGORITHM = env.str("JWT_ALGORITHM", "HS256")
JWT_EXPIRES = env.int("JWT_EXPIRES", 900)
SENTRY_DSN = env.str("SENTRY_DSN")
OAUTH_CLIENT_ID = env.str("OAUTH_CLIENT_ID")
OAUTH_CLIENT_SECRET = env.str("OAUTH_CLIENT_SECRET")
OAUTH_OIDC_ENDPOINT = env.str("OIDC_ENDPOINT")
